[package]
name = "wolflang"
version = "0.1.0"
edition = "2024"

[lib]
name = "wolflang"
path = "src/lib.rs"

[[bin]]
name = "wolflang"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

